# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: https://github.com/oca/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: Escodoo
org_slug: Escodoo
rebel_module_groups: []
repo_description: Escodoo add-ons used to extend or customize Odoo Account app functions
repo_name: Escodoo Account Addons
repo_slug: account-addons
repo_website: https://github.com/Escodoo/account-addons
travis_apt_packages: []
travis_apt_sources: []

